/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etf.openpgp.iu170057d_sm170081d;

import java.util.Iterator;

import java.nio.charset.StandardCharsets;

import etf.openpgp.iu170057d_sm170081d.utils.Utils;
import etf.openpgp.iu170057d_sm170081d.encryption.Encryption;
import etf.openpgp.iu170057d_sm170081d.encryption.PGPKeys;
import org.bouncycastle.util.encoders.Hex;
import org.bouncycastle.openpgp.PGPKeyRingGenerator;
import org.bouncycastle.openpgp.PGPPublicKeyRing;
import org.bouncycastle.openpgp.PGPPublicKeyRingCollection;
import org.bouncycastle.openpgp.PGPSecretKeyRing;
import org.bouncycastle.openpgp.PGPSecretKeyRingCollection;
import org.bouncycastle.openpgp.PGPPublicKey;
import org.bouncycastle.openpgp.PGPPrivateKey;
import org.bouncycastle.openpgp.PGPSecretKey;
import org.bouncycastle.openpgp.operator.jcajce.JcePBESecretKeyDecryptorBuilder;

/**
 *
 * @author Marko
 */
public class App extends javax.swing.JFrame {

    private String currentMessage = null;
    
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabs = new javax.swing.JTabbedPane();
        jSend_Tab = new javax.swing.JPanel();
        jSend_FromLabel = new javax.swing.JLabel();
        jSend_ToLabel = new javax.swing.JLabel();
        jSend_FromDropdown = new javax.swing.JComboBox<>();
        jSend_ToDropdown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSend_BodyTextarea = new javax.swing.JTextArea();
        jSend_SendButton = new javax.swing.JButton();
        jSend_SignatureLabel = new javax.swing.JLabel();
        jSend_SignatureTextbox = new javax.swing.JTextField();
        jSend_EncryptionLabel = new javax.swing.JLabel();
        jSend_EncryptionDropdown = new javax.swing.JComboBox<>();
        jSend_PassphraseLabel = new javax.swing.JLabel();
        jSend_CompressedCheckbox = new javax.swing.JCheckBox();
        jSend_EncodedCheckbox = new javax.swing.JCheckBox();
        jSend_TestButton = new javax.swing.JButton();
        jSend_PassphrasePasswordbox = new javax.swing.JPasswordField();
        jRecv_Tab = new javax.swing.JPanel();
        jRecv_FromLabel = new javax.swing.JLabel();
        jRecv_ToLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jRecv_BodyTextarea = new javax.swing.JTextArea();
        jRecv_OpenButton = new javax.swing.JButton();
        jRecv_SignatureLabel = new javax.swing.JLabel();
        jRecv_SignatureTextbox = new javax.swing.JTextField();
        jRecv_EncryptionLabel = new javax.swing.JLabel();
        jRecv_PassphraseLabel = new javax.swing.JLabel();
        jRecv_CompressedCheckbox = new javax.swing.JCheckBox();
        jRecv_EncodedCheckbox = new javax.swing.JCheckBox();
        jRecv_DecryptButton = new javax.swing.JButton();
        jRecv_EncryptionTextbox = new javax.swing.JTextField();
        jRecv_SaveButton = new javax.swing.JButton();
        jRecv_FromTextbox = new javax.swing.JTextField();
        jRecv_ToTextbox = new javax.swing.JTextField();
        jRecv_PassphrasePasswordbox = new javax.swing.JPasswordField();
        jCont_Tab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jCont_ContactsTable = new javax.swing.JTable();
        jCont_EmailLabel = new javax.swing.JLabel();
        jCont_EmailTextbox = new javax.swing.JTextField();
        jCont_KeyIdLabel = new javax.swing.JLabel();
        jCont_PublicKeyTextbox = new javax.swing.JTextField();
        jCont_PublicKeyImportButton = new javax.swing.JButton();
        jCont_CreatedLabel = new javax.swing.JLabel();
        jCont_KeyNameTextbox = new javax.swing.JTextField();
        jCont_KeyIdTextbox = new javax.swing.JTextField();
        jCont_EncrPrivateKeyLabel = new javax.swing.JLabel();
        jCont_PublicKeyLabel = new javax.swing.JLabel();
        jCont_CreatedTextbox = new javax.swing.JTextField();
        jCont_KeyNameLabel = new javax.swing.JLabel();
        jCont_EncrPrivateKeyTextbox = new javax.swing.JTextField();
        jCont_PublicKeyExportButton = new javax.swing.JButton();
        jCont_EncrPrivateKeyExportButton = new javax.swing.JButton();
        jCont_EncrPrivateKeyImportButton = new javax.swing.JButton();
        jCont_AlgorithmLabel = new javax.swing.JLabel();
        jCont_CancelButton = new javax.swing.JButton();
        jCont_OkButton = new javax.swing.JButton();
        jCont_AlgorithmDropdown = new javax.swing.JComboBox<>();
        jCont_PassphraseLabel = new javax.swing.JLabel();
        jCont_PassphrasePasswordbox = new javax.swing.JPasswordField();
        jStatusbar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pretty Good Privacy Client");
        setSize(new java.awt.Dimension(640, 480));

        jTabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabs.setDoubleBuffered(true);
        jTabs.setPreferredSize(new java.awt.Dimension(640, 480));

        jSend_Tab.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 30, 25, 30));

        jSend_FromLabel.setText("From");

        jSend_ToLabel.setText("To");

        jSend_FromDropdown.setMaximumRowCount(16);
        jSend_FromDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pera@gmail.com       |   AAAA AAAA BBBB BBBB", "pera@gmail.com       |   AB01 5912 7EFF 0DFD", "pera@gmail.com       |   za slanje zikinoj firmi", "pera@gmail.com       |   <no signature>", "pera@hotmail.com    |   ABCD EF012 3456 789A", "pera@hotmail.com    |   <no signature>", " " }));

        jSend_ToDropdown.setMaximumRowCount(16);
        jSend_ToDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "zika@gmail.com       |   FF01 FFFF FFFF BBBB", "zika@gmail.com       |   zikin glavni javni kljuc", "zika@hotmail.com    |   ABCD EF012 3456 789A", " " }));

        jSend_BodyTextarea.setColumns(20);
        jSend_BodyTextarea.setLineWrap(true);
        jSend_BodyTextarea.setTabSize(4);
        jSend_BodyTextarea.setName(""); // NOI18N
        jScrollPane1.setViewportView(jSend_BodyTextarea);

        jSend_SendButton.setText("Send");
        jSend_SendButton.setPreferredSize(new java.awt.Dimension(58, 32));
        jSend_SendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSend_SendButtonMouseClicked(evt);
            }
        });

        jSend_SignatureLabel.setText("Signature");

        jSend_SignatureTextbox.setEditable(false);
        jSend_SignatureTextbox.setText("DSA 4096");

        jSend_EncryptionLabel.setText("Encryption");

        jSend_EncryptionDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ElGamal + IDEA", "ElGamal + 3DES", "none" }));

        jSend_PassphraseLabel.setText("Passphrase");

        jSend_CompressedCheckbox.setSelected(true);
        jSend_CompressedCheckbox.setText("Compressed ");
        jSend_CompressedCheckbox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jSend_EncodedCheckbox.setSelected(true);
        jSend_EncodedCheckbox.setText("Encoded ");
        jSend_EncodedCheckbox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jSend_TestButton.setText("Test");

        jSend_PassphrasePasswordbox.setText("passphrase");

        javax.swing.GroupLayout jSend_TabLayout = new javax.swing.GroupLayout(jSend_Tab);
        jSend_Tab.setLayout(jSend_TabLayout);
        jSend_TabLayout.setHorizontalGroup(
            jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSend_TabLayout.createSequentialGroup()
                .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSend_FromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSend_ToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSend_FromDropdown, 0, 452, Short.MAX_VALUE)
                    .addComponent(jSend_ToDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSend_SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jSend_TabLayout.createSequentialGroup()
                .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSend_EncryptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSend_SignatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSend_EncryptionDropdown, 0, 194, Short.MAX_VALUE)
                    .addComponent(jSend_SignatureTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jSend_TabLayout.createSequentialGroup()
                        .addComponent(jSend_CompressedCheckbox)
                        .addGap(18, 18, 18)
                        .addComponent(jSend_EncodedCheckbox)
                        .addContainerGap())
                    .addGroup(jSend_TabLayout.createSequentialGroup()
                        .addComponent(jSend_PassphraseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSend_PassphrasePasswordbox, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSend_TestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jSend_TabLayout.setVerticalGroup(
            jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSend_TabLayout.createSequentialGroup()
                .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jSend_TabLayout.createSequentialGroup()
                        .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSend_FromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSend_FromDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSend_ToDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSend_ToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSend_SendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSend_TestButton)
                        .addComponent(jSend_PassphraseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSend_PassphrasePasswordbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSend_SignatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSend_SignatureTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSend_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSend_EncryptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSend_EncryptionDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSend_CompressedCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSend_EncodedCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabs.addTab("Send email", jSend_Tab);

        jRecv_Tab.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 30, 25, 30));

        jRecv_FromLabel.setText("From");

        jRecv_ToLabel.setText("To");

        jRecv_BodyTextarea.setEditable(false);
        jRecv_BodyTextarea.setColumns(20);
        jRecv_BodyTextarea.setTabSize(4);
        jScrollPane2.setViewportView(jRecv_BodyTextarea);

        jRecv_OpenButton.setText("Open");
        jRecv_OpenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRecv_OpenButtonMouseClicked(evt);
            }
        });

        jRecv_SignatureLabel.setText("Signature");

        jRecv_SignatureTextbox.setEditable(false);

        jRecv_EncryptionLabel.setText("Encryption");

        jRecv_PassphraseLabel.setText("Passphrase");

        jRecv_CompressedCheckbox.setSelected(true);
        jRecv_CompressedCheckbox.setText("Compressed ");
        jRecv_CompressedCheckbox.setEnabled(false);
        jRecv_CompressedCheckbox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jRecv_EncodedCheckbox.setSelected(true);
        jRecv_EncodedCheckbox.setText("Encoded ");
        jRecv_EncodedCheckbox.setEnabled(false);
        jRecv_EncodedCheckbox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jRecv_DecryptButton.setText("Decr.");

        jRecv_EncryptionTextbox.setEditable(false);

        jRecv_SaveButton.setText("Save");
        jRecv_SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRecv_SaveButtonMouseClicked(evt);
            }
        });

        jRecv_FromTextbox.setEditable(false);

        jRecv_ToTextbox.setEditable(false);

        jRecv_PassphrasePasswordbox.setText("passphrase");

        javax.swing.GroupLayout jRecv_TabLayout = new javax.swing.GroupLayout(jRecv_Tab);
        jRecv_Tab.setLayout(jRecv_TabLayout);
        jRecv_TabLayout.setHorizontalGroup(
            jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRecv_TabLayout.createSequentialGroup()
                .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRecv_FromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRecv_ToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRecv_FromTextbox)
                    .addComponent(jRecv_ToTextbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRecv_SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRecv_OpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jRecv_TabLayout.createSequentialGroup()
                .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRecv_EncryptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRecv_SignatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRecv_SignatureTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jRecv_EncryptionTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRecv_TabLayout.createSequentialGroup()
                        .addComponent(jRecv_CompressedCheckbox)
                        .addGap(18, 18, 18)
                        .addComponent(jRecv_EncodedCheckbox)
                        .addGap(31, 31, 31))
                    .addGroup(jRecv_TabLayout.createSequentialGroup()
                        .addComponent(jRecv_PassphraseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRecv_PassphrasePasswordbox, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRecv_DecryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jRecv_TabLayout.setVerticalGroup(
            jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRecv_TabLayout.createSequentialGroup()
                .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRecv_FromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRecv_FromTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRecv_OpenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRecv_ToTextbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRecv_ToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRecv_SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRecv_SignatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRecv_SignatureTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRecv_CompressedCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRecv_EncodedCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRecv_DecryptButton)
                        .addComponent(jRecv_PassphraseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRecv_PassphrasePasswordbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jRecv_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRecv_EncryptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRecv_EncryptionTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabs.addTab("Receive email", jRecv_Tab);

        jCont_Tab.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 30, 25, 30));

        jCont_ContactsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"_", "_", "_", "_", "_"}
            },
            new String [] {
                "Email", "Key id", "Key name", "Algorithm", "Created"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jCont_ContactsTable);

        jCont_EmailLabel.setText("Email");

        jCont_EmailTextbox.setEditable(false);

        jCont_KeyIdLabel.setText("Key id");

        jCont_PublicKeyTextbox.setEditable(false);

        jCont_PublicKeyImportButton.setText("Import");

        jCont_CreatedLabel.setText("Created");

        jCont_KeyIdTextbox.setEditable(false);

        jCont_EncrPrivateKeyLabel.setText("Encrypted private key");

        jCont_PublicKeyLabel.setText("Public key");

        jCont_CreatedTextbox.setEditable(false);

        jCont_KeyNameLabel.setText("Key name");

        jCont_EncrPrivateKeyTextbox.setEditable(false);

        jCont_PublicKeyExportButton.setText("Export");

        jCont_EncrPrivateKeyExportButton.setText("Export");

        jCont_EncrPrivateKeyImportButton.setText("Import");

        jCont_AlgorithmLabel.setText("Algorithm");

        jCont_CancelButton.setText("Cancel");

        jCont_OkButton.setText("OK");
        jCont_OkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCont_OkButtonMouseClicked(evt);
            }
        });

        jCont_AlgorithmDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ElGamal", "DSA" }));

        jCont_PassphraseLabel.setText("Passphrase");

        jCont_PassphrasePasswordbox.setText("passphrase");

        javax.swing.GroupLayout jCont_TabLayout = new javax.swing.GroupLayout(jCont_Tab);
        jCont_Tab.setLayout(jCont_TabLayout);
        jCont_TabLayout.setHorizontalGroup(
            jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCont_TabLayout.createSequentialGroup()
                .addComponent(jCont_EmailTextbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCont_KeyIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_KeyIdTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCont_KeyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_KeyNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
            .addGroup(jCont_TabLayout.createSequentialGroup()
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCont_PassphraseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jCont_TabLayout.createSequentialGroup()
                        .addComponent(jCont_PassphrasePasswordbox)
                        .addGap(6, 6, 6)))
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCont_AlgorithmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_AlgorithmDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCont_CreatedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_CreatedTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCont_TabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCont_OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCont_CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jCont_TabLayout.createSequentialGroup()
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCont_PublicKeyTextbox)
                    .addComponent(jCont_EncrPrivateKeyTextbox)
                    .addComponent(jCont_EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_PublicKeyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_EncrPrivateKeyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCont_EncrPrivateKeyExportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_PublicKeyExportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCont_PublicKeyImportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_EncrPrivateKeyImportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jCont_TabLayout.setVerticalGroup(
            jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCont_TabLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCont_EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_KeyIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_KeyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCont_EmailTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_KeyIdTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCont_KeyNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jCont_TabLayout.createSequentialGroup()
                            .addComponent(jCont_PassphraseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(jCont_PassphrasePasswordbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCont_TabLayout.createSequentialGroup()
                            .addComponent(jCont_CreatedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jCont_CreatedTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jCont_TabLayout.createSequentialGroup()
                        .addComponent(jCont_AlgorithmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jCont_AlgorithmDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCont_PublicKeyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCont_PublicKeyImportButton)
                    .addComponent(jCont_PublicKeyExportButton)
                    .addComponent(jCont_PublicKeyTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCont_EncrPrivateKeyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCont_EncrPrivateKeyImportButton)
                    .addComponent(jCont_EncrPrivateKeyExportButton)
                    .addComponent(jCont_EncrPrivateKeyTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jCont_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCont_OkButton)
                    .addComponent(jCont_CancelButton))
                .addGap(0, 0, 0))
        );

        jTabs.addTab("Contacts", jCont_Tab);

        jStatusbar.setEditable(false);
        jStatusbar.setText("Success");
        jStatusbar.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jStatusbar)
            .addComponent(jTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jStatusbar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSend_SendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSend_SendButtonMouseClicked
        // Read original message
        String textMessage = jSend_BodyTextarea.getText();
        byte[] byteMessage = textMessage.getBytes();
        
        // Read encryption metadata
        boolean confidentiality = false;
        boolean signature = false;
        boolean compression = false;
        boolean conversionToRadix64 = false;
        
        byte[] senderSignaturePrivateKey = Hex.decode("e04fd020ea3a6910a2d808002b30309d");
        byte[] senderConfidentialityPublicKey = Hex.decode("e04fd020ea3a6910a2d808002b30309d");
        
        Encryption.SymmetricEncrptionAlgorithm encryptionAlgorithm = Encryption.SymmetricEncrptionAlgorithm.NONE;
        
        byte[] senderPassphrase = Hex.decode("e04fd020ea3a6910a2d808002b30309d");
        
        // Encryption
        byte[] encryptedMessage = Encryption.encrypt(
                byteMessage,
                senderSignaturePrivateKey,
                senderConfidentialityPublicKey,
                encryptionAlgorithm,
                senderPassphrase,
                confidentiality,
                signature,
                compression,
                conversionToRadix64);
        
        // TODO(Marko): Read the actual file path in a new dialog
        String encryptedFilePath = "C:\\Users\\User\\Desktop\\test.txt";
        
        // Store file
        Utils.writeToFile(encryptedFilePath, encryptedMessage);
        
        System.out.println("INFO: Stored encrypted file.");
    }//GEN-LAST:event_jSend_SendButtonMouseClicked

    private void jRecv_OpenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRecv_OpenButtonMouseClicked
        // TODO(Marko): Read the actual file path in a new dialog
        String encryptedFilePath = "C:\\Users\\User\\Desktop\\test.txt";
        
        // Decryption metadata
        byte[] encryptedMessage = Utils.readFromFile(encryptedFilePath);
        byte[] receiverPassphrase = Hex.decode("e04fd020ea3a6910a2d808002b30309d");
        
        // Read key values
        byte[] senderPublicKey = Hex.decode("e04fd020ea3a6910a2d808002b30309d");
        byte[] receiverPrivateKey = Hex.decode("e04fd020ea3a6910a2d808002b30309d");
        
        // Decryption
        Encryption.DecryptedMessage decryptedMessage = Encryption.decrypt(
                encryptedMessage,
                senderPublicKey,
                receiverPrivateKey);
        String dectryptedMessage = new String(decryptedMessage.decryptedMessage);
        
        // Write output
        jRecv_BodyTextarea.setText(dectryptedMessage);
        currentMessage = dectryptedMessage;
    }//GEN-LAST:event_jRecv_OpenButtonMouseClicked

    private void jRecv_SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRecv_SaveButtonMouseClicked
        if (currentMessage == null) {
            System.out.println("Trenutno nema primljene poruke.");
            return;
        }
        
        // TODO(Marko): Read the actual file path in a new dialog
        String decryptedFilePath = "C:\\Users\\User\\Desktop\\received.txt";
        
        Utils.writeToFile(decryptedFilePath, currentMessage.getBytes());
    }//GEN-LAST:event_jRecv_SaveButtonMouseClicked

    private void jCont_OkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCont_OkButtonMouseClicked
        String name = "";
        String email = "";
        Encryption.AsymmetricEncrptionAlgorithm encryptionAlgorithm = Encryption.AsymmetricEncrptionAlgorithm.DSA;
        byte[] passphrase = Hex.decode("e04fd020ea3a6910a2d808002b30309d");
        
        Encryption.PublicPrivateKeyPair pk = Encryption.generateKeyPair(
                encryptionAlgorithm,
                passphrase
        );
    }//GEN-LAST:event_jCont_OkButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        try {
            // Get secret and public key ring collections
            System.out.println("Get secret and public key ring collections");
            PGPSecretKeyRingCollection secretKeyRing = PGPKeys.getSecretKeysCollection();
            PGPPublicKeyRingCollection publicKeyRing = PGPKeys.getPublicKeysCollection();
            
            // Print all private key rings from the private key ring collection
            System.out.println("Print all private key rings from the private key ring collection");
            Iterator<PGPSecretKeyRing> keyRingIter = PGPKeys.getSecretKeysCollection().getKeyRings();
	          
            while (keyRingIter.hasNext()) {
                PGPSecretKeyRing keyRing = keyRingIter.next();
	                    
                Iterator<PGPSecretKey> keyIter = keyRing.getSecretKeys();
                PGPSecretKey key = keyIter.next();
                PGPPrivateKey privateKey = key.extractPrivateKey(new JcePBESecretKeyDecryptorBuilder().setProvider("BC").build("Sifra123".toCharArray()));
                PGPPublicKey  publicKey = key.getPublicKey();
                System.out.println(Integer.toHexString((int) key.getKeyID()) + " " + key.getUserIDs().next());
            }
            
            // Print all public key rings from the public key ring collection
            System.out.println("Print all public key rings from the public key ring collection");
            Iterator<PGPPublicKeyRing> keyRingIter2 = PGPKeys.getPublicKeysCollection().getKeyRings();
            while (keyRingIter2.hasNext()) {
                PGPPublicKeyRing keyRing = keyRingIter2.next();

                Iterator<PGPPublicKey> keyIter = keyRing.getPublicKeys();
                PGPPublicKey key = keyIter.next();

                System.out.println(Integer.toHexString((int) key.getKeyID()) + " " + key.getRawUserIDs().next());
            }
            
            // Create new public and private key rings
            System.out.println("Create new public and private key rings");
            String name1 = "Nikola Vucenovic <nikolavucenovic97@gmail.com>";
            String password1 = "Sifra123";
            String name2 = "Milo Tomasevic <milo@gmail.com>";
            String password2 = "Sifra123";
            PGPKeyRingGenerator pgpKeyRingGenerator1 = PGPKeys.createPGPKeyRingGenerator(
                    PGPKeys.generateDsaKeyPair(1024),
                    PGPKeys.generateElGamalKeyPair(1024),
                    name1,
                    password1.toCharArray());
            PGPKeyRingGenerator pgpKeyRingGenerator2 = PGPKeys.createPGPKeyRingGenerator(
                    PGPKeys.generateDsaKeyPair(1024),
                    PGPKeys.generateElGamalKeyPair(1024),
                    name2,
                    password2.toCharArray());
            
            // Add private key to private key collection
            System.out.println("Add private key to private key collection");
            PGPKeys.addSecretKey(pgpKeyRingGenerator1);
            
            // Add public key to public key collection
            System.out.println("Add public key to public key collection");
            PGPKeys.addPublicKey(pgpKeyRingGenerator1);
            
            // Store private key ring collection
            System.out.println("Store private key ring collection");
            PGPKeys.saveSecretKeysToFile();
            
            // Store public key ring collection
            System.out.println("Store public key ring collection");
            PGPKeys.savePublicKeysToFile();
            
        } catch(Exception e) {
            e.printStackTrace();
        }
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCont_AlgorithmDropdown;
    private javax.swing.JLabel jCont_AlgorithmLabel;
    private javax.swing.JButton jCont_CancelButton;
    private javax.swing.JTable jCont_ContactsTable;
    private javax.swing.JLabel jCont_CreatedLabel;
    private javax.swing.JTextField jCont_CreatedTextbox;
    private javax.swing.JLabel jCont_EmailLabel;
    private javax.swing.JTextField jCont_EmailTextbox;
    private javax.swing.JButton jCont_EncrPrivateKeyExportButton;
    private javax.swing.JButton jCont_EncrPrivateKeyImportButton;
    private javax.swing.JLabel jCont_EncrPrivateKeyLabel;
    private javax.swing.JTextField jCont_EncrPrivateKeyTextbox;
    private javax.swing.JLabel jCont_KeyIdLabel;
    private javax.swing.JTextField jCont_KeyIdTextbox;
    private javax.swing.JLabel jCont_KeyNameLabel;
    private javax.swing.JTextField jCont_KeyNameTextbox;
    private javax.swing.JButton jCont_OkButton;
    private javax.swing.JLabel jCont_PassphraseLabel;
    private javax.swing.JPasswordField jCont_PassphrasePasswordbox;
    private javax.swing.JButton jCont_PublicKeyExportButton;
    private javax.swing.JButton jCont_PublicKeyImportButton;
    private javax.swing.JLabel jCont_PublicKeyLabel;
    private javax.swing.JTextField jCont_PublicKeyTextbox;
    private javax.swing.JPanel jCont_Tab;
    private javax.swing.JTextArea jRecv_BodyTextarea;
    private javax.swing.JCheckBox jRecv_CompressedCheckbox;
    private javax.swing.JButton jRecv_DecryptButton;
    private javax.swing.JCheckBox jRecv_EncodedCheckbox;
    private javax.swing.JLabel jRecv_EncryptionLabel;
    private javax.swing.JTextField jRecv_EncryptionTextbox;
    private javax.swing.JLabel jRecv_FromLabel;
    private javax.swing.JTextField jRecv_FromTextbox;
    private javax.swing.JButton jRecv_OpenButton;
    private javax.swing.JLabel jRecv_PassphraseLabel;
    private javax.swing.JPasswordField jRecv_PassphrasePasswordbox;
    private javax.swing.JButton jRecv_SaveButton;
    private javax.swing.JLabel jRecv_SignatureLabel;
    private javax.swing.JTextField jRecv_SignatureTextbox;
    private javax.swing.JPanel jRecv_Tab;
    private javax.swing.JLabel jRecv_ToLabel;
    private javax.swing.JTextField jRecv_ToTextbox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jSend_BodyTextarea;
    private javax.swing.JCheckBox jSend_CompressedCheckbox;
    private javax.swing.JCheckBox jSend_EncodedCheckbox;
    private javax.swing.JComboBox<String> jSend_EncryptionDropdown;
    private javax.swing.JLabel jSend_EncryptionLabel;
    private javax.swing.JComboBox<String> jSend_FromDropdown;
    private javax.swing.JLabel jSend_FromLabel;
    private javax.swing.JLabel jSend_PassphraseLabel;
    private javax.swing.JPasswordField jSend_PassphrasePasswordbox;
    private javax.swing.JButton jSend_SendButton;
    private javax.swing.JLabel jSend_SignatureLabel;
    private javax.swing.JTextField jSend_SignatureTextbox;
    private javax.swing.JPanel jSend_Tab;
    private javax.swing.JButton jSend_TestButton;
    private javax.swing.JComboBox<String> jSend_ToDropdown;
    private javax.swing.JLabel jSend_ToLabel;
    private javax.swing.JTextField jStatusbar;
    private javax.swing.JTabbedPane jTabs;
    // End of variables declaration//GEN-END:variables
}
